// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_ERM.Erm.DataAccess.ErmDbContext;

#nullable disable

namespace Project_ERM.Migrations
{
    [DbContext(typeof(ErmDbContext))]
    [Migration("20240411183949_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_ERM.Erm.DataAccess.BusinessProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BusinessProcess", (string)null);
                });

            modelBuilder.Entity("Project_ERM.Erm.DataAccess.RiskProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("Description");

                    b.Property<int>("OccurrenceProbability")
                        .HasColumnType("INTEGER)")
                        .HasColumnName("OccurrenceProbability");

                    b.Property<int>("PotentialBusinessImpact")
                        .HasColumnType("INTEGER)")
                        .HasColumnName("PotentialBusinessImpact");

                    b.Property<string>("PotentialSolution")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("PotentialSolution");

                    b.Property<string>("RiskName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.ToTable("RiskProfile", (string)null);
                });

            modelBuilder.Entity("Project_ERM.Erm.DataAccess.RiskProfile", b =>
                {
                    b.HasOne("Project_ERM.Erm.DataAccess.BusinessProcess", "BusinessProcess")
                        .WithMany("RiskProfiles")
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("Project_ERM.Erm.DataAccess.BusinessProcess", b =>
                {
                    b.Navigation("RiskProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
